### PR TITLE
docker-compose.yml, fix permission issues

### PR DESCRIPTION
**Pull request by 1ma**
- removed code container, because the code can be shared with the host with a regular volume in the php container.
- refactored nginx build into a simple image import. instead of COPYing the vhost file in a Dockerfile, link the local nginx/conf.d with the one inside the container using a volume.
- removed all usages of `links:`, since all containers live inside the same virtual network they are not needed.
- replaced php image with letsbonus/php-dev:7.0, which solves the permission problems by running the slave PHP-FPM processes as root.
- remove exposure of ports 9000 and 6379 into the host machine. The host machine does not need access to these ports, only the containers, which they already have.

### CODE REVIEW

**Comment by jorge07** [comment]
Mis dies

**Comment by 1ma** [comment]
BTW why the RDBMS hate? No MySQL, no PostgreSQL, no nothing? :P

**Comment by jorge07** [comment]
I'll update the documentation after merge

**Comment by jorge07** [comment]
@1ma this is a starter kit, Redis is on the pack to store sessions and have the configuration ready. If you need other thinks, added on your project. ;)

**Pull request merged**
